package com.ynotscript.trackme.api.db.ibatis.models;

import com.ynotscript.trackme.api.configuration.MainConfiguration;
import com.ynotscript.trackme.api.db.ibatis.dynamic.PrefixedTableName;

public class Application implements PrefixedTableName {
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column trackme_application.id_application
	 * @ibatorgenerated  Wed Jun 01 13:12:35 CEST 2011
	 */
	private Integer idApplication;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column trackme_application.id_application_partner
	 * @ibatorgenerated  Wed Jun 01 13:12:35 CEST 2011
	 */
	private String applicationPartnerId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column trackme_application.version
	 * @ibatorgenerated  Wed Jun 01 13:12:35 CEST 2011
	 */
	private String version;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column trackme_application.name
	 * @ibatorgenerated  Wed Jun 01 13:12:35 CEST 2011
	 */
	private String name;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column trackme_application.id_partner
	 * @ibatorgenerated  Wed Jun 01 13:12:35 CEST 2011
	 */
	private Integer partnerId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column trackme_application.id_operating_system
	 * @ibatorgenerated  Wed Jun 01 13:12:35 CEST 2011
	 */
	private Integer operatingSystemId;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column trackme_application.id_application
	 * @return  the value of trackme_application.id_application
	 * @ibatorgenerated  Wed Jun 01 13:12:35 CEST 2011
	 */
	public Integer getIdApplication() {
		return idApplication;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column trackme_application.id_application
	 * @param idApplication  the value for trackme_application.id_application
	 * @ibatorgenerated  Wed Jun 01 13:12:35 CEST 2011
	 */
	public void setIdApplication(Integer idApplication) {
		this.idApplication = idApplication;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column trackme_application.id_application_partner
	 * @return  the value of trackme_application.id_application_partner
	 * @ibatorgenerated  Wed Jun 01 13:12:35 CEST 2011
	 */
	public String getApplicationPartnerId() {
		return applicationPartnerId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column trackme_application.id_application_partner
	 * @param applicationPartnerId  the value for trackme_application.id_application_partner
	 * @ibatorgenerated  Wed Jun 01 13:12:35 CEST 2011
	 */
	public void setApplicationPartnerId(String applicationPartnerId) {
		this.applicationPartnerId = applicationPartnerId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column trackme_application.version
	 * @return  the value of trackme_application.version
	 * @ibatorgenerated  Wed Jun 01 13:12:35 CEST 2011
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column trackme_application.version
	 * @param version  the value for trackme_application.version
	 * @ibatorgenerated  Wed Jun 01 13:12:35 CEST 2011
	 */
	public void setVersion(String version) {
		this.version = version;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column trackme_application.name
	 * @return  the value of trackme_application.name
	 * @ibatorgenerated  Wed Jun 01 13:12:35 CEST 2011
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column trackme_application.name
	 * @param name  the value for trackme_application.name
	 * @ibatorgenerated  Wed Jun 01 13:12:35 CEST 2011
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column trackme_application.id_partner
	 * @return  the value of trackme_application.id_partner
	 * @ibatorgenerated  Wed Jun 01 13:12:35 CEST 2011
	 */
	public Integer getPartnerId() {
		return partnerId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column trackme_application.id_partner
	 * @param partnerId  the value for trackme_application.id_partner
	 * @ibatorgenerated  Wed Jun 01 13:12:35 CEST 2011
	 */
	public void setPartnerId(Integer partnerId) {
		this.partnerId = partnerId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column trackme_application.id_operating_system
	 * @return  the value of trackme_application.id_operating_system
	 * @ibatorgenerated  Wed Jun 01 13:12:35 CEST 2011
	 */
	public Integer getOperatingSystemId() {
		return operatingSystemId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column trackme_application.id_operating_system
	 * @param operatingSystemId  the value for trackme_application.id_operating_system
	 * @ibatorgenerated  Wed Jun 01 13:12:35 CEST 2011
	 */
	public void setOperatingSystemId(Integer operatingSystemId) {
		this.operatingSystemId = operatingSystemId;
	}

	private String prefix = MainConfiguration.getConfiguration()
			.getString(MainConfiguration.Db.DB_TABLE_PREFIX);

	@Override
	public final String getPrefix() {
		return prefix;
	}

	@Override
	public final void setPrefix(final String prefix) {
		this.prefix = prefix;
	}
}