package com.ynotscript.trackme.api.db.ibatis.models;

import com.ynotscript.trackme.api.configuration.MainConfiguration;
import com.ynotscript.trackme.api.db.ibatis.dynamic.PrefixedTableName;

public class Handset implements PrefixedTableName {
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column trackme_handset.id_handset
	 * @ibatorgenerated  Wed Jun 01 13:12:44 CEST 2011
	 */
	private Integer handsetId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column trackme_handset.id_handset_partner
	 * @ibatorgenerated  Wed Jun 01 13:12:44 CEST 2011
	 */
	private String handsetPartnerId;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column trackme_handset.id_handset
	 * @return  the value of trackme_handset.id_handset
	 * @ibatorgenerated  Wed Jun 01 13:12:44 CEST 2011
	 */
	public Integer getHandsetId() {
		return handsetId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column trackme_handset.id_handset
	 * @param handsetId  the value for trackme_handset.id_handset
	 * @ibatorgenerated  Wed Jun 01 13:12:44 CEST 2011
	 */
	public void setHandsetId(Integer handsetId) {
		this.handsetId = handsetId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column trackme_handset.id_handset_partner
	 * @return  the value of trackme_handset.id_handset_partner
	 * @ibatorgenerated  Wed Jun 01 13:12:44 CEST 2011
	 */
	public String getHandsetPartnerId() {
		return handsetPartnerId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column trackme_handset.id_handset_partner
	 * @param handsetPartnerId  the value for trackme_handset.id_handset_partner
	 * @ibatorgenerated  Wed Jun 01 13:12:44 CEST 2011
	 */
	public void setHandsetPartnerId(String handsetPartnerId) {
		this.handsetPartnerId = handsetPartnerId;
	}

	private String prefix = MainConfiguration.getConfiguration()
			.getString(MainConfiguration.Db.DB_TABLE_PREFIX);

	@Override
	public final String getPrefix() {
		return prefix;
	}

	@Override
	public final void setPrefix(final String prefix) {
		this.prefix = prefix;
	}
}