package com.ynotscript.trackme.api.db.ibatis.models;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.ynotscript.trackme.api.configuration.MainConfiguration;
import com.ynotscript.trackme.api.db.ibatis.dynamic.PrefixedTableName;

public class HandsetHasApplicationExample implements PrefixedTableName {
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table trackme_handset_has_application
	 * @ibatorgenerated  Wed Jun 01 13:30:44 CEST 2011
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table trackme_handset_has_application
	 * @ibatorgenerated  Wed Jun 01 13:30:44 CEST 2011
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trackme_handset_has_application
	 * @ibatorgenerated  Wed Jun 01 13:30:44 CEST 2011
	 */
	public HandsetHasApplicationExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trackme_handset_has_application
	 * @ibatorgenerated  Wed Jun 01 13:30:44 CEST 2011
	 */
	protected HandsetHasApplicationExample(HandsetHasApplicationExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trackme_handset_has_application
	 * @ibatorgenerated  Wed Jun 01 13:30:44 CEST 2011
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trackme_handset_has_application
	 * @ibatorgenerated  Wed Jun 01 13:30:44 CEST 2011
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trackme_handset_has_application
	 * @ibatorgenerated  Wed Jun 01 13:30:44 CEST 2011
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trackme_handset_has_application
	 * @ibatorgenerated  Wed Jun 01 13:30:44 CEST 2011
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trackme_handset_has_application
	 * @ibatorgenerated  Wed Jun 01 13:30:44 CEST 2011
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trackme_handset_has_application
	 * @ibatorgenerated  Wed Jun 01 13:30:44 CEST 2011
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trackme_handset_has_application
	 * @ibatorgenerated  Wed Jun 01 13:30:44 CEST 2011
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table trackme_handset_has_application
	 * @ibatorgenerated  Wed Jun 01 13:30:44 CEST 2011
	 */
	public static class Criteria {
		protected List<String> criteriaWithoutValue;
		protected List<Map<String, Object>> criteriaWithSingleValue;
		protected List<Map<String, Object>> criteriaWithListValue;
		protected List<Map<String, Object>> criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList<String>();
			criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
			criteriaWithListValue = new ArrayList<Map<String, Object>>();
			criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List<String> getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List<Map<String, Object>> getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List<Map<String, Object>> getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List<Map<String, Object>> getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition,
				List<? extends Object> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List<Object> list = new ArrayList<Object>();
			list.add(value1);
			list.add(value2);
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andApplicationIdIsNull() {
			addCriterion("id_application is null");
			return this;
		}

		public Criteria andApplicationIdIsNotNull() {
			addCriterion("id_application is not null");
			return this;
		}

		public Criteria andApplicationIdEqualTo(Integer value) {
			addCriterion("id_application =", value, "applicationId");
			return this;
		}

		public Criteria andApplicationIdNotEqualTo(Integer value) {
			addCriterion("id_application <>", value, "applicationId");
			return this;
		}

		public Criteria andApplicationIdGreaterThan(Integer value) {
			addCriterion("id_application >", value, "applicationId");
			return this;
		}

		public Criteria andApplicationIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_application >=", value, "applicationId");
			return this;
		}

		public Criteria andApplicationIdLessThan(Integer value) {
			addCriterion("id_application <", value, "applicationId");
			return this;
		}

		public Criteria andApplicationIdLessThanOrEqualTo(Integer value) {
			addCriterion("id_application <=", value, "applicationId");
			return this;
		}

		public Criteria andApplicationIdIn(List<Integer> values) {
			addCriterion("id_application in", values, "applicationId");
			return this;
		}

		public Criteria andApplicationIdNotIn(List<Integer> values) {
			addCriterion("id_application not in", values, "applicationId");
			return this;
		}

		public Criteria andApplicationIdBetween(Integer value1, Integer value2) {
			addCriterion("id_application between", value1, value2,
					"applicationId");
			return this;
		}

		public Criteria andApplicationIdNotBetween(Integer value1,
				Integer value2) {
			addCriterion("id_application not between", value1, value2,
					"applicationId");
			return this;
		}

		public Criteria andHandsetIdIsNull() {
			addCriterion("id_handset is null");
			return this;
		}

		public Criteria andHandsetIdIsNotNull() {
			addCriterion("id_handset is not null");
			return this;
		}

		public Criteria andHandsetIdEqualTo(Integer value) {
			addCriterion("id_handset =", value, "handsetId");
			return this;
		}

		public Criteria andHandsetIdNotEqualTo(Integer value) {
			addCriterion("id_handset <>", value, "handsetId");
			return this;
		}

		public Criteria andHandsetIdGreaterThan(Integer value) {
			addCriterion("id_handset >", value, "handsetId");
			return this;
		}

		public Criteria andHandsetIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_handset >=", value, "handsetId");
			return this;
		}

		public Criteria andHandsetIdLessThan(Integer value) {
			addCriterion("id_handset <", value, "handsetId");
			return this;
		}

		public Criteria andHandsetIdLessThanOrEqualTo(Integer value) {
			addCriterion("id_handset <=", value, "handsetId");
			return this;
		}

		public Criteria andHandsetIdIn(List<Integer> values) {
			addCriterion("id_handset in", values, "handsetId");
			return this;
		}

		public Criteria andHandsetIdNotIn(List<Integer> values) {
			addCriterion("id_handset not in", values, "handsetId");
			return this;
		}

		public Criteria andHandsetIdBetween(Integer value1, Integer value2) {
			addCriterion("id_handset between", value1, value2, "handsetId");
			return this;
		}

		public Criteria andHandsetIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id_handset not between", value1, value2, "handsetId");
			return this;
		}

		public Criteria andNumberOfUseIsNull() {
			addCriterion("number_of_use is null");
			return this;
		}

		public Criteria andNumberOfUseIsNotNull() {
			addCriterion("number_of_use is not null");
			return this;
		}

		public Criteria andNumberOfUseEqualTo(Integer value) {
			addCriterion("number_of_use =", value, "numberOfUse");
			return this;
		}

		public Criteria andNumberOfUseNotEqualTo(Integer value) {
			addCriterion("number_of_use <>", value, "numberOfUse");
			return this;
		}

		public Criteria andNumberOfUseGreaterThan(Integer value) {
			addCriterion("number_of_use >", value, "numberOfUse");
			return this;
		}

		public Criteria andNumberOfUseGreaterThanOrEqualTo(Integer value) {
			addCriterion("number_of_use >=", value, "numberOfUse");
			return this;
		}

		public Criteria andNumberOfUseLessThan(Integer value) {
			addCriterion("number_of_use <", value, "numberOfUse");
			return this;
		}

		public Criteria andNumberOfUseLessThanOrEqualTo(Integer value) {
			addCriterion("number_of_use <=", value, "numberOfUse");
			return this;
		}

		public Criteria andNumberOfUseIn(List<Integer> values) {
			addCriterion("number_of_use in", values, "numberOfUse");
			return this;
		}

		public Criteria andNumberOfUseNotIn(List<Integer> values) {
			addCriterion("number_of_use not in", values, "numberOfUse");
			return this;
		}

		public Criteria andNumberOfUseBetween(Integer value1, Integer value2) {
			addCriterion("number_of_use between", value1, value2, "numberOfUse");
			return this;
		}

		public Criteria andNumberOfUseNotBetween(Integer value1, Integer value2) {
			addCriterion("number_of_use not between", value1, value2,
					"numberOfUse");
			return this;
		}
	}

	private String prefix = MainConfiguration.getConfiguration()
			.getString(MainConfiguration.Db.DB_TABLE_PREFIX);

	@Override
	public final String getPrefix() {
		return prefix;
	}

	@Override
	public final void setPrefix(final String prefix) {
		this.prefix = prefix;
	}
}