package com.ynotscript.trackme.api.db.ibatis.models;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.ynotscript.trackme.api.configuration.MainConfiguration;
import com.ynotscript.trackme.api.db.ibatis.dynamic.PrefixedTableName;

public class HandsetExample implements PrefixedTableName {
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table trackme_handset
	 * @ibatorgenerated  Wed Jun 01 13:12:44 CEST 2011
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table trackme_handset
	 * @ibatorgenerated  Wed Jun 01 13:12:44 CEST 2011
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trackme_handset
	 * @ibatorgenerated  Wed Jun 01 13:12:44 CEST 2011
	 */
	public HandsetExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trackme_handset
	 * @ibatorgenerated  Wed Jun 01 13:12:44 CEST 2011
	 */
	protected HandsetExample(HandsetExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trackme_handset
	 * @ibatorgenerated  Wed Jun 01 13:12:44 CEST 2011
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trackme_handset
	 * @ibatorgenerated  Wed Jun 01 13:12:44 CEST 2011
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trackme_handset
	 * @ibatorgenerated  Wed Jun 01 13:12:44 CEST 2011
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trackme_handset
	 * @ibatorgenerated  Wed Jun 01 13:12:44 CEST 2011
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trackme_handset
	 * @ibatorgenerated  Wed Jun 01 13:12:44 CEST 2011
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trackme_handset
	 * @ibatorgenerated  Wed Jun 01 13:12:44 CEST 2011
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trackme_handset
	 * @ibatorgenerated  Wed Jun 01 13:12:44 CEST 2011
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table trackme_handset
	 * @ibatorgenerated  Wed Jun 01 13:12:44 CEST 2011
	 */
	public static class Criteria {
		protected List<String> criteriaWithoutValue;
		protected List<Map<String, Object>> criteriaWithSingleValue;
		protected List<Map<String, Object>> criteriaWithListValue;
		protected List<Map<String, Object>> criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList<String>();
			criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
			criteriaWithListValue = new ArrayList<Map<String, Object>>();
			criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List<String> getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List<Map<String, Object>> getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List<Map<String, Object>> getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List<Map<String, Object>> getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition,
				List<? extends Object> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List<Object> list = new ArrayList<Object>();
			list.add(value1);
			list.add(value2);
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andHandsetIdIsNull() {
			addCriterion("id_handset is null");
			return this;
		}

		public Criteria andHandsetIdIsNotNull() {
			addCriterion("id_handset is not null");
			return this;
		}

		public Criteria andHandsetIdEqualTo(Integer value) {
			addCriterion("id_handset =", value, "handsetId");
			return this;
		}

		public Criteria andHandsetIdNotEqualTo(Integer value) {
			addCriterion("id_handset <>", value, "handsetId");
			return this;
		}

		public Criteria andHandsetIdGreaterThan(Integer value) {
			addCriterion("id_handset >", value, "handsetId");
			return this;
		}

		public Criteria andHandsetIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_handset >=", value, "handsetId");
			return this;
		}

		public Criteria andHandsetIdLessThan(Integer value) {
			addCriterion("id_handset <", value, "handsetId");
			return this;
		}

		public Criteria andHandsetIdLessThanOrEqualTo(Integer value) {
			addCriterion("id_handset <=", value, "handsetId");
			return this;
		}

		public Criteria andHandsetIdIn(List<Integer> values) {
			addCriterion("id_handset in", values, "handsetId");
			return this;
		}

		public Criteria andHandsetIdNotIn(List<Integer> values) {
			addCriterion("id_handset not in", values, "handsetId");
			return this;
		}

		public Criteria andHandsetIdBetween(Integer value1, Integer value2) {
			addCriterion("id_handset between", value1, value2, "handsetId");
			return this;
		}

		public Criteria andHandsetIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id_handset not between", value1, value2, "handsetId");
			return this;
		}

		public Criteria andHandsetPartnerIdIsNull() {
			addCriterion("id_handset_partner is null");
			return this;
		}

		public Criteria andHandsetPartnerIdIsNotNull() {
			addCriterion("id_handset_partner is not null");
			return this;
		}

		public Criteria andHandsetPartnerIdEqualTo(String value) {
			addCriterion("id_handset_partner =", value, "handsetPartnerId");
			return this;
		}

		public Criteria andHandsetPartnerIdNotEqualTo(String value) {
			addCriterion("id_handset_partner <>", value, "handsetPartnerId");
			return this;
		}

		public Criteria andHandsetPartnerIdGreaterThan(String value) {
			addCriterion("id_handset_partner >", value, "handsetPartnerId");
			return this;
		}

		public Criteria andHandsetPartnerIdGreaterThanOrEqualTo(String value) {
			addCriterion("id_handset_partner >=", value, "handsetPartnerId");
			return this;
		}

		public Criteria andHandsetPartnerIdLessThan(String value) {
			addCriterion("id_handset_partner <", value, "handsetPartnerId");
			return this;
		}

		public Criteria andHandsetPartnerIdLessThanOrEqualTo(String value) {
			addCriterion("id_handset_partner <=", value, "handsetPartnerId");
			return this;
		}

		public Criteria andHandsetPartnerIdLike(String value) {
			addCriterion("id_handset_partner like", value, "handsetPartnerId");
			return this;
		}

		public Criteria andHandsetPartnerIdNotLike(String value) {
			addCriterion("id_handset_partner not like", value,
					"handsetPartnerId");
			return this;
		}

		public Criteria andHandsetPartnerIdIn(List<String> values) {
			addCriterion("id_handset_partner in", values, "handsetPartnerId");
			return this;
		}

		public Criteria andHandsetPartnerIdNotIn(List<String> values) {
			addCriterion("id_handset_partner not in", values,
					"handsetPartnerId");
			return this;
		}

		public Criteria andHandsetPartnerIdBetween(String value1, String value2) {
			addCriterion("id_handset_partner between", value1, value2,
					"handsetPartnerId");
			return this;
		}

		public Criteria andHandsetPartnerIdNotBetween(String value1,
				String value2) {
			addCriterion("id_handset_partner not between", value1, value2,
					"handsetPartnerId");
			return this;
		}
	}

	private String prefix = MainConfiguration.getConfiguration()
			.getString(MainConfiguration.Db.DB_TABLE_PREFIX);

	@Override
	public final String getPrefix() {
		return prefix;
	}

	@Override
	public final void setPrefix(final String prefix) {
		this.prefix = prefix;
	}
}