package com.ynotscript.trackme.api.db.ibatis.models;

import com.ynotscript.trackme.api.configuration.MainConfiguration;
import com.ynotscript.trackme.api.db.ibatis.dynamic.PrefixedTableName;

public class HandsetHasApplication implements PrefixedTableName {
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column trackme_handset_has_application.id_application
	 * @ibatorgenerated  Wed Jun 01 13:30:44 CEST 2011
	 */
	private Integer applicationId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column trackme_handset_has_application.id_handset
	 * @ibatorgenerated  Wed Jun 01 13:30:44 CEST 2011
	 */
	private Integer handsetId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column trackme_handset_has_application.number_of_use
	 * @ibatorgenerated  Wed Jun 01 13:30:44 CEST 2011
	 */
	private Integer numberOfUse;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column trackme_handset_has_application.id_application
	 * @return  the value of trackme_handset_has_application.id_application
	 * @ibatorgenerated  Wed Jun 01 13:30:44 CEST 2011
	 */
	public Integer getApplicationId() {
		return applicationId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column trackme_handset_has_application.id_application
	 * @param applicationId  the value for trackme_handset_has_application.id_application
	 * @ibatorgenerated  Wed Jun 01 13:30:44 CEST 2011
	 */
	public void setApplicationId(Integer applicationId) {
		this.applicationId = applicationId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column trackme_handset_has_application.id_handset
	 * @return  the value of trackme_handset_has_application.id_handset
	 * @ibatorgenerated  Wed Jun 01 13:30:44 CEST 2011
	 */
	public Integer getHandsetId() {
		return handsetId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column trackme_handset_has_application.id_handset
	 * @param handsetId  the value for trackme_handset_has_application.id_handset
	 * @ibatorgenerated  Wed Jun 01 13:30:44 CEST 2011
	 */
	public void setHandsetId(Integer handsetId) {
		this.handsetId = handsetId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column trackme_handset_has_application.number_of_use
	 * @return  the value of trackme_handset_has_application.number_of_use
	 * @ibatorgenerated  Wed Jun 01 13:30:44 CEST 2011
	 */
	public Integer getNumberOfUse() {
		return numberOfUse;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column trackme_handset_has_application.number_of_use
	 * @param numberOfUse  the value for trackme_handset_has_application.number_of_use
	 * @ibatorgenerated  Wed Jun 01 13:30:44 CEST 2011
	 */
	public void setNumberOfUse(Integer numberOfUse) {
		this.numberOfUse = numberOfUse;
	}

	private String prefix = MainConfiguration.getConfiguration()
			.getString(MainConfiguration.Db.DB_TABLE_PREFIX);

	@Override
	public final String getPrefix() {
		return prefix;
	}

	@Override
	public final void setPrefix(final String prefix) {
		this.prefix = prefix;
	}
}