package com.ynotscript.trackme.api.db.ibatis.models;

import com.ynotscript.trackme.api.configuration.MainConfiguration;
import com.ynotscript.trackme.api.db.ibatis.dynamic.PrefixedTableName;

public class OperatingSystem implements PrefixedTableName {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column trackme_operating_system.id_operating_system
	 * @ibatorgenerated  Wed Jun 01 13:12:47 CEST 2011
	 */
	private Integer operatingSystemId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column trackme_operating_system.name
	 * @ibatorgenerated  Wed Jun 01 13:12:47 CEST 2011
	 */
	private String name;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column trackme_operating_system.version
	 * @ibatorgenerated  Wed Jun 01 13:12:47 CEST 2011
	 */
	private String version;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column trackme_operating_system.id_operating_system
	 * @return  the value of trackme_operating_system.id_operating_system
	 * @ibatorgenerated  Wed Jun 01 13:12:47 CEST 2011
	 */
	public Integer getOperatingSystemId() {
		return operatingSystemId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column trackme_operating_system.id_operating_system
	 * @param operatingSystemId  the value for trackme_operating_system.id_operating_system
	 * @ibatorgenerated  Wed Jun 01 13:12:47 CEST 2011
	 */
	public void setOperatingSystemId(Integer operatingSystemId) {
		this.operatingSystemId = operatingSystemId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column trackme_operating_system.name
	 * @return  the value of trackme_operating_system.name
	 * @ibatorgenerated  Wed Jun 01 13:12:47 CEST 2011
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column trackme_operating_system.name
	 * @param name  the value for trackme_operating_system.name
	 * @ibatorgenerated  Wed Jun 01 13:12:47 CEST 2011
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column trackme_operating_system.version
	 * @return  the value of trackme_operating_system.version
	 * @ibatorgenerated  Wed Jun 01 13:12:47 CEST 2011
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column trackme_operating_system.version
	 * @param version  the value for trackme_operating_system.version
	 * @ibatorgenerated  Wed Jun 01 13:12:47 CEST 2011
	 */
	public void setVersion(String version) {
		this.version = version;
	}

	private String prefix = MainConfiguration.getConfiguration()
			.getString(MainConfiguration.Db.DB_TABLE_PREFIX);

	@Override
	public final String getPrefix() {
		return prefix;
	}

	@Override
	public final void setPrefix(final String prefix) {
		this.prefix = prefix;
	}
}