package com.ynotscript.trackme.api.db.ibatis.models;

import com.ynotscript.trackme.api.configuration.MainConfiguration;
import com.ynotscript.trackme.api.db.ibatis.dynamic.PrefixedTableName;

public class Partner implements PrefixedTableName {
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column trackme_partner.id_partner
	 * @ibatorgenerated  Wed Jun 01 13:12:55 CEST 2011
	 */
	private Integer partnerId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column trackme_partner.name
	 * @ibatorgenerated  Wed Jun 01 13:12:55 CEST 2011
	 */
	private String name;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column trackme_partner.id_partner
	 * @return  the value of trackme_partner.id_partner
	 * @ibatorgenerated  Wed Jun 01 13:12:55 CEST 2011
	 */
	public Integer getPartnerId() {
		return partnerId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column trackme_partner.id_partner
	 * @param partnerId  the value for trackme_partner.id_partner
	 * @ibatorgenerated  Wed Jun 01 13:12:55 CEST 2011
	 */
	public void setPartnerId(Integer partnerId) {
		this.partnerId = partnerId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column trackme_partner.name
	 * @return  the value of trackme_partner.name
	 * @ibatorgenerated  Wed Jun 01 13:12:55 CEST 2011
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column trackme_partner.name
	 * @param name  the value for trackme_partner.name
	 * @ibatorgenerated  Wed Jun 01 13:12:55 CEST 2011
	 */
	public void setName(String name) {
		this.name = name;
	}

	private String prefix = MainConfiguration.getConfiguration()
			.getString(MainConfiguration.Db.DB_TABLE_PREFIX);

	@Override
	public final String getPrefix() {
		return prefix;
	}

	@Override
	public final void setPrefix(final String prefix) {
		this.prefix = prefix;
	}
}