package com.ynotscript.trackme.api.db.ibatis.daos;

import com.ynotscript.trackme.api.db.ibatis.models.Application;
import com.ynotscript.trackme.api.db.ibatis.models.ApplicationExample;
import java.sql.SQLException;
import java.util.List;

public interface ApplicationDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_application
     *
     * @ibatorgenerated Wed Jun 01 13:12:35 CEST 2011
     */
    int countByExample(ApplicationExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_application
     *
     * @ibatorgenerated Wed Jun 01 13:12:35 CEST 2011
     */
    int deleteByExample(ApplicationExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_application
     *
     * @ibatorgenerated Wed Jun 01 13:12:35 CEST 2011
     */
    int deleteByPrimaryKey(Integer idApplication) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_application
     *
     * @ibatorgenerated Wed Jun 01 13:12:35 CEST 2011
     */
    Integer insert(Application record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_application
     *
     * @ibatorgenerated Wed Jun 01 13:12:35 CEST 2011
     */
    Integer insertSelective(Application record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_application
     *
     * @ibatorgenerated Wed Jun 01 13:12:35 CEST 2011
     */
    List<Application> selectByExample(ApplicationExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_application
     *
     * @ibatorgenerated Wed Jun 01 13:12:35 CEST 2011
     */
    Application selectByPrimaryKey(Integer idApplication) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_application
     *
     * @ibatorgenerated Wed Jun 01 13:12:35 CEST 2011
     */
    int updateByExampleSelective(Application record, ApplicationExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_application
     *
     * @ibatorgenerated Wed Jun 01 13:12:35 CEST 2011
     */
    int updateByExample(Application record, ApplicationExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_application
     *
     * @ibatorgenerated Wed Jun 01 13:12:35 CEST 2011
     */
    int updateByPrimaryKeySelective(Application record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_application
     *
     * @ibatorgenerated Wed Jun 01 13:12:35 CEST 2011
     */
    int updateByPrimaryKey(Application record) throws SQLException;
}