package com.ynotscript.trackme.api.db.ibatis.daos;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ynotscript.trackme.api.db.ibatis.models.Application;
import com.ynotscript.trackme.api.db.ibatis.models.ApplicationExample;
import java.sql.SQLException;
import java.util.List;

public class ApplicationDAOImpl implements ApplicationDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table trackme_application
     *
     * @ibatorgenerated Wed Jun 01 13:12:35 CEST 2011
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_application
     *
     * @ibatorgenerated Wed Jun 01 13:12:35 CEST 2011
     */
    public ApplicationDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_application
     *
     * @ibatorgenerated Wed Jun 01 13:12:35 CEST 2011
     */
    public void setSqlMapClient(SqlMapClient sqlMapClient) {
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_application
     *
     * @ibatorgenerated Wed Jun 01 13:12:35 CEST 2011
     */
    public SqlMapClient getSqlMapClient() {
        return sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_application
     *
     * @ibatorgenerated Wed Jun 01 13:12:35 CEST 2011
     */
    public int countByExample(ApplicationExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("$prefix$application.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_application
     *
     * @ibatorgenerated Wed Jun 01 13:12:35 CEST 2011
     */
    public int deleteByExample(ApplicationExample example) throws SQLException {
        int rows = sqlMapClient.delete("$prefix$application.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_application
     *
     * @ibatorgenerated Wed Jun 01 13:12:35 CEST 2011
     */
    public int deleteByPrimaryKey(Integer idApplication) throws SQLException {
        Application key = new Application();
        key.setIdApplication(idApplication);
        int rows = sqlMapClient.delete("$prefix$application.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_application
     *
     * @ibatorgenerated Wed Jun 01 13:12:35 CEST 2011
     */
    public Integer insert(Application record) throws SQLException {
        Object newKey = sqlMapClient.insert("$prefix$application.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_application
     *
     * @ibatorgenerated Wed Jun 01 13:12:35 CEST 2011
     */
    public Integer insertSelective(Application record) throws SQLException {
        Object newKey = sqlMapClient.insert("$prefix$application.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_application
     *
     * @ibatorgenerated Wed Jun 01 13:12:35 CEST 2011
     */
    @SuppressWarnings("unchecked")
    public List<Application> selectByExample(ApplicationExample example) throws SQLException {
        List<Application> list = sqlMapClient.queryForList("$prefix$application.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_application
     *
     * @ibatorgenerated Wed Jun 01 13:12:35 CEST 2011
     */
    public Application selectByPrimaryKey(Integer idApplication) throws SQLException {
        Application key = new Application();
        key.setIdApplication(idApplication);
        Application record = (Application) sqlMapClient.queryForObject("$prefix$application.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_application
     *
     * @ibatorgenerated Wed Jun 01 13:12:35 CEST 2011
     */
    public int updateByExampleSelective(Application record, ApplicationExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("$prefix$application.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_application
     *
     * @ibatorgenerated Wed Jun 01 13:12:35 CEST 2011
     */
    public int updateByExample(Application record, ApplicationExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("$prefix$application.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_application
     *
     * @ibatorgenerated Wed Jun 01 13:12:35 CEST 2011
     */
    public int updateByPrimaryKeySelective(Application record) throws SQLException {
        int rows = sqlMapClient.update("$prefix$application.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_application
     *
     * @ibatorgenerated Wed Jun 01 13:12:35 CEST 2011
     */
    public int updateByPrimaryKey(Application record) throws SQLException {
        int rows = sqlMapClient.update("$prefix$application.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table trackme_application
     *
     * @ibatorgenerated Wed Jun 01 13:12:35 CEST 2011
     */
    private static class UpdateByExampleParms extends ApplicationExample {
        private Object record;

        public UpdateByExampleParms(Object record, ApplicationExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}