package com.ynotscript.trackme.api.db.ibatis.daos;

import com.ynotscript.trackme.api.db.ibatis.models.HandsetHasApplication;
import com.ynotscript.trackme.api.db.ibatis.models.HandsetHasApplicationExample;
import java.sql.SQLException;
import java.util.List;

public interface HandsetHasApplicationDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_handset_has_application
     *
     * @ibatorgenerated Wed Jun 01 13:30:44 CEST 2011
     */
    int countByExample(HandsetHasApplicationExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_handset_has_application
     *
     * @ibatorgenerated Wed Jun 01 13:30:44 CEST 2011
     */
    int deleteByExample(HandsetHasApplicationExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_handset_has_application
     *
     * @ibatorgenerated Wed Jun 01 13:30:44 CEST 2011
     */
    int deleteByPrimaryKey(Integer applicationId, Integer handsetId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_handset_has_application
     *
     * @ibatorgenerated Wed Jun 01 13:30:44 CEST 2011
     */
    void insert(HandsetHasApplication record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_handset_has_application
     *
     * @ibatorgenerated Wed Jun 01 13:30:44 CEST 2011
     */
    void insertSelective(HandsetHasApplication record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_handset_has_application
     *
     * @ibatorgenerated Wed Jun 01 13:30:44 CEST 2011
     */
    List<HandsetHasApplication> selectByExample(HandsetHasApplicationExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_handset_has_application
     *
     * @ibatorgenerated Wed Jun 01 13:30:44 CEST 2011
     */
    HandsetHasApplication selectByPrimaryKey(Integer applicationId, Integer handsetId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_handset_has_application
     *
     * @ibatorgenerated Wed Jun 01 13:30:44 CEST 2011
     */
    int updateByExampleSelective(HandsetHasApplication record, HandsetHasApplicationExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_handset_has_application
     *
     * @ibatorgenerated Wed Jun 01 13:30:44 CEST 2011
     */
    int updateByExample(HandsetHasApplication record, HandsetHasApplicationExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_handset_has_application
     *
     * @ibatorgenerated Wed Jun 01 13:30:44 CEST 2011
     */
    int updateByPrimaryKeySelective(HandsetHasApplication record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_handset_has_application
     *
     * @ibatorgenerated Wed Jun 01 13:30:44 CEST 2011
     */
    int updateByPrimaryKey(HandsetHasApplication record) throws SQLException;
}