package com.ynotscript.trackme.api.db.ibatis.daos;

import com.ynotscript.trackme.api.db.ibatis.models.Handset;
import com.ynotscript.trackme.api.db.ibatis.models.HandsetExample;
import java.sql.SQLException;
import java.util.List;

public interface HandsetDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_handset
     *
     * @ibatorgenerated Wed Jun 01 13:12:44 CEST 2011
     */
    int countByExample(HandsetExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_handset
     *
     * @ibatorgenerated Wed Jun 01 13:12:44 CEST 2011
     */
    int deleteByExample(HandsetExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_handset
     *
     * @ibatorgenerated Wed Jun 01 13:12:44 CEST 2011
     */
    int deleteByPrimaryKey(Integer handsetId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_handset
     *
     * @ibatorgenerated Wed Jun 01 13:12:44 CEST 2011
     */
    Integer insert(Handset record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_handset
     *
     * @ibatorgenerated Wed Jun 01 13:12:44 CEST 2011
     */
    Integer insertSelective(Handset record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_handset
     *
     * @ibatorgenerated Wed Jun 01 13:12:44 CEST 2011
     */
    List<Handset> selectByExample(HandsetExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_handset
     *
     * @ibatorgenerated Wed Jun 01 13:12:44 CEST 2011
     */
    Handset selectByPrimaryKey(Integer handsetId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_handset
     *
     * @ibatorgenerated Wed Jun 01 13:12:44 CEST 2011
     */
    int updateByExampleSelective(Handset record, HandsetExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_handset
     *
     * @ibatorgenerated Wed Jun 01 13:12:44 CEST 2011
     */
    int updateByExample(Handset record, HandsetExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_handset
     *
     * @ibatorgenerated Wed Jun 01 13:12:44 CEST 2011
     */
    int updateByPrimaryKeySelective(Handset record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_handset
     *
     * @ibatorgenerated Wed Jun 01 13:12:44 CEST 2011
     */
    int updateByPrimaryKey(Handset record) throws SQLException;
}