package com.ynotscript.trackme.api.db.ibatis.daos;

import com.ynotscript.trackme.api.db.ibatis.models.OperatingSystem;
import com.ynotscript.trackme.api.db.ibatis.models.OperatingSystemExample;
import java.sql.SQLException;
import java.util.List;

public interface OperatingSystemDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_operating_system
     *
     * @ibatorgenerated Wed Jun 01 13:12:47 CEST 2011
     */
    int countByExample(OperatingSystemExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_operating_system
     *
     * @ibatorgenerated Wed Jun 01 13:12:47 CEST 2011
     */
    int deleteByExample(OperatingSystemExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_operating_system
     *
     * @ibatorgenerated Wed Jun 01 13:12:47 CEST 2011
     */
    int deleteByPrimaryKey(Integer operatingSystemId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_operating_system
     *
     * @ibatorgenerated Wed Jun 01 13:12:47 CEST 2011
     */
    Integer insert(OperatingSystem record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_operating_system
     *
     * @ibatorgenerated Wed Jun 01 13:12:47 CEST 2011
     */
    Integer insertSelective(OperatingSystem record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_operating_system
     *
     * @ibatorgenerated Wed Jun 01 13:12:47 CEST 2011
     */
    List<OperatingSystem> selectByExample(OperatingSystemExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_operating_system
     *
     * @ibatorgenerated Wed Jun 01 13:12:47 CEST 2011
     */
    OperatingSystem selectByPrimaryKey(Integer operatingSystemId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_operating_system
     *
     * @ibatorgenerated Wed Jun 01 13:12:47 CEST 2011
     */
    int updateByExampleSelective(OperatingSystem record, OperatingSystemExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_operating_system
     *
     * @ibatorgenerated Wed Jun 01 13:12:47 CEST 2011
     */
    int updateByExample(OperatingSystem record, OperatingSystemExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_operating_system
     *
     * @ibatorgenerated Wed Jun 01 13:12:47 CEST 2011
     */
    int updateByPrimaryKeySelective(OperatingSystem record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_operating_system
     *
     * @ibatorgenerated Wed Jun 01 13:12:47 CEST 2011
     */
    int updateByPrimaryKey(OperatingSystem record) throws SQLException;
}