package com.ynotscript.trackme.api.db.ibatis.daos;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ynotscript.trackme.api.db.ibatis.models.Partner;
import com.ynotscript.trackme.api.db.ibatis.models.PartnerExample;
import java.sql.SQLException;
import java.util.List;

public class PartnerDAOImpl implements PartnerDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table trackme_partner
     *
     * @ibatorgenerated Wed Jun 01 13:12:55 CEST 2011
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_partner
     *
     * @ibatorgenerated Wed Jun 01 13:12:55 CEST 2011
     */
    public PartnerDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_partner
     *
     * @ibatorgenerated Wed Jun 01 13:12:55 CEST 2011
     */
    public void setSqlMapClient(SqlMapClient sqlMapClient) {
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_partner
     *
     * @ibatorgenerated Wed Jun 01 13:12:55 CEST 2011
     */
    public SqlMapClient getSqlMapClient() {
        return sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_partner
     *
     * @ibatorgenerated Wed Jun 01 13:12:55 CEST 2011
     */
    public int countByExample(PartnerExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("$prefix$partner.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_partner
     *
     * @ibatorgenerated Wed Jun 01 13:12:55 CEST 2011
     */
    public int deleteByExample(PartnerExample example) throws SQLException {
        int rows = sqlMapClient.delete("$prefix$partner.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_partner
     *
     * @ibatorgenerated Wed Jun 01 13:12:55 CEST 2011
     */
    public int deleteByPrimaryKey(Integer partnerId) throws SQLException {
        Partner key = new Partner();
        key.setPartnerId(partnerId);
        int rows = sqlMapClient.delete("$prefix$partner.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_partner
     *
     * @ibatorgenerated Wed Jun 01 13:12:55 CEST 2011
     */
    public Integer insert(Partner record) throws SQLException {
        Object newKey = sqlMapClient.insert("$prefix$partner.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_partner
     *
     * @ibatorgenerated Wed Jun 01 13:12:55 CEST 2011
     */
    public Integer insertSelective(Partner record) throws SQLException {
        Object newKey = sqlMapClient.insert("$prefix$partner.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_partner
     *
     * @ibatorgenerated Wed Jun 01 13:12:55 CEST 2011
     */
    @SuppressWarnings("unchecked")
    public List<Partner> selectByExample(PartnerExample example) throws SQLException {
        List<Partner> list = sqlMapClient.queryForList("$prefix$partner.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_partner
     *
     * @ibatorgenerated Wed Jun 01 13:12:55 CEST 2011
     */
    public Partner selectByPrimaryKey(Integer partnerId) throws SQLException {
        Partner key = new Partner();
        key.setPartnerId(partnerId);
        Partner record = (Partner) sqlMapClient.queryForObject("$prefix$partner.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_partner
     *
     * @ibatorgenerated Wed Jun 01 13:12:55 CEST 2011
     */
    public int updateByExampleSelective(Partner record, PartnerExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("$prefix$partner.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_partner
     *
     * @ibatorgenerated Wed Jun 01 13:12:55 CEST 2011
     */
    public int updateByExample(Partner record, PartnerExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("$prefix$partner.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_partner
     *
     * @ibatorgenerated Wed Jun 01 13:12:55 CEST 2011
     */
    public int updateByPrimaryKeySelective(Partner record) throws SQLException {
        int rows = sqlMapClient.update("$prefix$partner.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_partner
     *
     * @ibatorgenerated Wed Jun 01 13:12:55 CEST 2011
     */
    public int updateByPrimaryKey(Partner record) throws SQLException {
        int rows = sqlMapClient.update("$prefix$partner.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table trackme_partner
     *
     * @ibatorgenerated Wed Jun 01 13:12:55 CEST 2011
     */
    private static class UpdateByExampleParms extends PartnerExample {
        private Object record;

        public UpdateByExampleParms(Object record, PartnerExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}