package com.ynotscript.trackme.api.db.ibatis.daos;

import com.ynotscript.trackme.api.db.ibatis.models.Partner;
import com.ynotscript.trackme.api.db.ibatis.models.PartnerExample;
import java.sql.SQLException;
import java.util.List;

public interface PartnerDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_partner
     *
     * @ibatorgenerated Wed Jun 01 13:12:55 CEST 2011
     */
    int countByExample(PartnerExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_partner
     *
     * @ibatorgenerated Wed Jun 01 13:12:55 CEST 2011
     */
    int deleteByExample(PartnerExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_partner
     *
     * @ibatorgenerated Wed Jun 01 13:12:55 CEST 2011
     */
    int deleteByPrimaryKey(Integer partnerId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_partner
     *
     * @ibatorgenerated Wed Jun 01 13:12:55 CEST 2011
     */
    Integer insert(Partner record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_partner
     *
     * @ibatorgenerated Wed Jun 01 13:12:55 CEST 2011
     */
    Integer insertSelective(Partner record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_partner
     *
     * @ibatorgenerated Wed Jun 01 13:12:55 CEST 2011
     */
    List<Partner> selectByExample(PartnerExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_partner
     *
     * @ibatorgenerated Wed Jun 01 13:12:55 CEST 2011
     */
    Partner selectByPrimaryKey(Integer partnerId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_partner
     *
     * @ibatorgenerated Wed Jun 01 13:12:55 CEST 2011
     */
    int updateByExampleSelective(Partner record, PartnerExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_partner
     *
     * @ibatorgenerated Wed Jun 01 13:12:55 CEST 2011
     */
    int updateByExample(Partner record, PartnerExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_partner
     *
     * @ibatorgenerated Wed Jun 01 13:12:55 CEST 2011
     */
    int updateByPrimaryKeySelective(Partner record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table trackme_partner
     *
     * @ibatorgenerated Wed Jun 01 13:12:55 CEST 2011
     */
    int updateByPrimaryKey(Partner record) throws SQLException;
}